version: "3.7"

services:
  randimals:
    image: universalanimalapi:latest
    container_name: randimals
    restart: always
    expose:
      - "80"
    volumes:
      - randimals:/var/www/html/animals

volumes:
  randimals:
